version: "2.0"
services:
  nginx:
    container_name: nginx_hr
    build:
      context: nginx/.
      dockerfile: Dockerfile
      # args:
        # USE_SSL: '1'
    image: hospitalrun_nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - hospitalrun
    volumes:
      - ./data/nginx/cert:/etc/nginx/cert
    restart: always

  hospitalrun:
    container_name: hospitalrun
    build:
      context: hospitalrun/.
      dockerfile: Dockerfile
    image: hospitalrun
    volumes:
      - ./data/hospitalrun/patientimages:/opt/hospitalrun/patientimages
      - ./data/hospitalrun/attachments:/opt/hospitalrun/attachments
    ports:
      - "3000:3000"
    links:
      - couchdb
      - elasticsearch
      - logstash
    depends_on:
      - couchdb
      - elasticsearch
      - logstash
    restart: always

  couchdb:
    container_name: couchdb_hr
    image: couchdb:1
    volumes:
      - ./data/couchdb/db:/usr/local/var/lib/couchdb
      - ./data/couchdb/conf:/usr/local/etc/couchdb/local.d
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=couchadmin
      - COUCHDB_PASSWORD=test
    restart: always

  elasticsearch:
    container_name: elasticsearch_hr
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    restart: always

  logstash:
    container_name: logstash_hr
    build: logstash/
    image: hospitalrun_logstash
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./logstash/config/:/usr/share/logstash/config/
    links:
      - couchdb
      - elasticsearch
    environment:
      - log.level=info
    restart: always
